AWSTemplateFormatVersion: '2010-09-09'
Description: Demo stack for enabling xray tracing on an apigateway stage
Resources:
  DemoApi:
    Properties:
      StageName: demo
    Type: AWS::Serverless::Api
  DemoFunction:
    Properties:
      CodeUri: s3://binxio-apigateway-custom-provider-eu-west-1/09e15066c934fb647723a930f63f7313
      Events:
        Hello:
          Properties:
            Method: GET
            Path: /hello
            RestApiId:
              Ref: DemoApi
          Type: Api
      Handler: index.handler
      InlineCode: "def handler(request, context):\n  return {\n    'statusCode': 200,\n\
        \    'body': 'Hello World! Please trace this.'\n  }\n"
      Runtime: python3.6
      Tracing: Active
    Type: AWS::Serverless::Function
  EnableXray:
    DependsOn: DemoApi
    Properties:
      RestApiId:
        Ref: DemoApi
      ServiceToken:
        Fn::Sub: arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:binxio-cfn-apigateway-provider
      StageName:
        Ref: DemoApi.Stage
    Type: Custom::EnableStageTracing
Transform: AWS::Serverless-2016-10-31
